### ISSUE TITLE
Scraper doesn't work with current data format

### ISSUE THREAD

**Issue by zacharysyoung** [JKSenthil/covid19-spread-tracker#1]
The current data can look something like this:

```
'Dutchess', '+33', '82', '+1', '1', '1.2%',
'Monroe', '+22', '68', '1', '1.5%',
'Erie', '56', '0', '0%',
```

Dutches has 6 fields since it saw increases in cases and deaths; Monroe has 5 fields since it saw an increase in only cases; and Erie has 4 fields because it has no increases in either cases or deaths.

I forked and added an `extract_counties_and_cases()` function which can handle these differences.  If you want, I can send a PR.

Otherwise, thanks! This project saved me and some friends a LOT of time!

**Comment by JKSenthil** [comment]
Great work! Yes, please do a PR when you have a chance!

**Comment by zacharysyoung** [comment]
Created PR, #2 

This will also change the resulting format to include cases and deaths, per county:
```
{"STATE_NAME":
  {
    "COUNTY_NAME": [CASES, DEATHS],
    ...
  },
  ...
}
```
